apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: mybookstore
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - name: http
      port: 3005
      targetPort: 3005
    - name: grpc
      port: 50055
      targetPort: 50055
