apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: mybookstore
spec:
  type: ClusterIP
  selector:
    app: orders-service
  ports:
    - name: http
      port: 3006
      targetPort: 3006
