apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  namespace: mybookstore
spec:
  type: ClusterIP
  selector:
    app: reviews-service
  ports:
    - name: http
      port: 3004
      targetPort: 3004
