apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: mybookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: 562448928616.dkr.ecr.us-east-1.amazonaws.com/mybookstore/users-service:latest
          ports:
            - name: http
              containerPort: 3002
            - name: grpc
              containerPort: 50052
          env:
            - name: HTTP_PORT
              value: "3002"
            - name: GRPC_PORT
              value: "50052"
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: app-secrets, key: JWT_SECRET } }
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: app-secrets, key: USERS_DATABASE_URL } }
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }
