apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: mybookstore
spec:
  type: ClusterIP
  selector:
    app: users-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
    - name: grpc
      port: 50052
      targetPort: 50052
