name: mybookstore-lambdas
runtime: nodejs
config:
  aws:region:
    value: us-east-1
  dataStackName:
    default: mybookstore-data/dev
  jwtSecret:
    secret: true
  labRoleName:
    default: LabRole
